name: Android Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  setup-java:
    runs-on: ubuntu-latest
    name: Set up Java

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

  build:
    runs-on: ubuntu-latest
    needs: setup-java

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew assembleDebug # Modify this according to your build command

  test:
    runs-on: ubuntu-latest
    needs: setup-java

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test # Modify this according to your test command

  lint:
    runs-on: ubuntu-latest
    needs: setup-java

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run lint checks
        run: ./gradlew lint # Modify this according to your lint command