name: AndroidBuild
on:
  push:
    branches:
      - main

jobs:
  setup-java:
    runs-on: ubuntu-latest
    name: Set up Java

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Change this to your desired Java version

  build:
    runs-on: ubuntu-latest
    needs: setup-java

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew assembleDebug # Modify this according to your build command

  test:
    runs-on: ubuntu-latest
    needs: setup-java

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test # Modify this according to your test command

  lint:
    runs-on: ubuntu-latest
    needs: setup-java

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run lint checks
        run: ./gradlew lint # Modify this according to your lint command