name: AndroidBuild

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup and Checkout
        uses: ./.github/actions/action.yml

      # Add more steps for your build process here
      # For example:
      - name: Build with Gradle
        run: ./gradlew build