name: AndroidBuild
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1


      - run: echo $JAVA_HOME

