name: AndroidBuild
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    name: Setup and Build
    env:
      JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  additional-job:
    runs-on: ubuntu-latest
    name: Another Job Using Java
    needs: setup-and-build
    env:
      JAVA_HOME: ${{ needs.setup-and-build.outputs.java-home }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set Java Home to Java 17
        run: |
          echo "Java 17 is installed at $JAVA_HOME"
          export JAVA_HOME=$(echo "$JAVA_HOME")
          echo "Java Home has been set to $JAVA_HOME"