name: AndroidBuild
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-java:
    runs-on: ubuntu-latest
    name: Set up Java
    outputs:
      java-home: ${{ steps.setup-java.outputs.java-home }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

  build:
    runs-on: ubuntu-latest
    name: Build and Test
    needs: setup-java
    env:
      JAVA_HOME: ${{ needs.setup-java.outputs.java-home }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
      - name: Set Java Home to Java 17
        run: |
          echo "Java 17 is installed at $JAVA_HOME"
          export JAVA_HOME=$(echo "$JAVA_HOME")
          echo "Java Home has been set to $JAVA_HOME"